/mob/living/simple_animal/hostile/megafauna/drop_loot()
	if(enraged || prob(75))
		return ..()
	if(length(loot))
		var/list/blacklist = list(/datum/nothing, /obj/effect/decal/cleanable/blood/gibs/bubblegum)
		for(var/L as anything in loot)
			if(L in blacklist)
				return ..()
		new /obj/structure/closet/crate/necropolis/tendril(loc)

/mob/living/simple_animal/hostile/megafauna/ancient_robot/drop_loot()
	if(enraged || prob(75))
		return ..()
	if(length(loot))
		var/list/blacklist = list(/datum/nothing, /obj/effect/decal/cleanable/blood/gibs/bubblegum)
		for(var/L as anything in loot)
			if(L in blacklist)
				return ..()
		new /obj/structure/closet/crate/necropolis/tendril(loc)

/mob/living/simple_animal/hostile/megafauna/dragon/space_dragon/drop_loot()
	return ..()

/mob/living/simple_animal/hostile/megafauna/fleshling/drop_loot()
	return ..()

/mob/living/simple_animal/hostile/megafauna/bubblegum/drop_loot()
	if(!enraged)
		return ..()
	var/crate_type = pick(loot)
	var/obj/structure/closet/crate/C = new crate_type(loc)
	new /obj/item/melee/spellblade/random(C)

/obj/structure/closet/crate/necropolis/bubblegum/populate_contents()
	new /obj/item/clothing/suit/space/hostile_environment(src)
	new /obj/item/clothing/head/helmet/space/hostile_environment(src)
