//Hydration levels for humans.
#define HYDRATION_LEVEL_FULL 550
#define HYDRATION_LEVEL_WELL_FED 450
#define HYDRATION_LEVEL_GOOD 350
#define HYDRATION_LEVEL_MEDIUM 250
#define HYDRATION_LEVEL_SMALL 150
#define HYDRATION_LEVEL_INEFFICIENT 100
#define HYDRATION_LEVEL_CURSED 0

#define ui_hydration "EAST-1:28,CENTER-3:11"
