#undef HYDRATION_LEVEL_FULL
#undef HYDRATION_LEVEL_WELL_FED
#undef HYDRATION_LEVEL_GOOD
#undef HYDRATION_LEVEL_MEDIUM
#undef HYDRATION_LEVEL_SMALL
#undef HYDRATION_LEVEL_INEFFICIENT
#undef HYDRATION_LEVEL_CURSED

#undef ui_hydration

#undef THIRST_FACTOR
#undef TRAIT_NO_THIRST
