name: "Label"

on:
- pull_request_target

jobs:
  labeler:
    runs-on: self-hosted
    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
